/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MiniJar;

import org.junit.Test;

import minijar.MiniJar;

import static org.junit.Assert.*;

public class MiniJarTest {
    @Test public void testSomeLibraryMethod() {
        MiniJar classUnderTest = new MiniJar();
        //ssertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
